/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 src/components/spaceship_cb1.gltf --transform --types --out src/components/StarFighterGLTF.tsx 
Files: src/components/spaceship_cb1.gltf [63.57KB] > /home/tanjir/sandbox/3d_portfolio/spaceship_cb1-transformed.glb [1.04MB] (-1531%)
Author: Lezalit (https://sketchfab.com/Lezalit)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/spaceship-cb1-4a8fddf9fadf4d2998925ca4b6d4b93b
Title: SPACESHIP - CB1
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type ActionName = 'Armature.002|Armature.002Action'

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName
}

type GLTFResult = GLTF & {
  nodes: {
    Cylinder004_Material_0: THREE.Mesh
    Cylinder006_Material_0: THREE.Mesh
    Cube011_Material_0: THREE.Mesh
    Cube018_Material_0: THREE.Mesh
    Cylinder005_Material_0: THREE.Mesh
    Cylinder003_Material_0: THREE.Mesh
    Cylinder010_Material_0: THREE.Mesh
    Cube023_Material_0: THREE.Mesh
    Cube012_Material_0: THREE.Mesh
    Cube003_Material_0: THREE.Mesh
    Cylinder001_Material_0: THREE.Mesh
    Cube027_Material_0: THREE.Mesh
    Cylinder009_Material_0: THREE.Mesh
    Cube_Material_0: THREE.Mesh
  }
  materials: {
    Material: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const group = React.useRef<THREE.Group>()
  const { nodes, materials, animations } = useGLTF('/spaceship_cb1-transformed.glb') as GLTFResult
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="_rootJoint" position={[-20.608, 0, 0]} rotation={[-Math.PI / 2, 0, 0]}>
          <group name="Bone_01" position={[-2.542, 9.772, -1.339]} rotation={[1.566, 0, -Math.PI / 2]}>
            <group name="Cylinder004" position={[-4.205, -1.453, 9.772]} rotation={[-Math.PI / 2, -1.571, 0]}>
              <mesh name="Cylinder004_Material_0" geometry={nodes.Cylinder004_Material_0.geometry} material={materials.Material} />
            </group>
          </group>
          <group name="Bone001_02" position={[-2.179, -9.772, -1.339]} rotation={[1.566, 0, -Math.PI / 2]}>
            <group name="Cylinder006" position={[-4.205, -1.815, -9.772]} rotation={[-Math.PI / 2, -1.571, 0]}>
              <mesh name="Cylinder006_Material_0" geometry={nodes.Cylinder006_Material_0.geometry} material={materials.Material} />
            </group>
          </group>
          <group name="Bone002_03" position={[-10.993, 22.977, 0.344]} rotation={[0, Math.PI / 2, 0]}>
            <group name="Cube011" position={[-2.522, -25.665, 6.999]} rotation={[0, -Math.PI / 2, 0]}>
              <mesh name="Cube011_Material_0" geometry={nodes.Cube011_Material_0.geometry} material={materials.Material} />
            </group>
          </group>
          <group name="Bone003_04" position={[-12.659, -24.643, 0.344]} rotation={[-Math.PI, 1.571, 0]}>
            <group name="Cube018" position={[2.522, -27.331, 8.665]} rotation={[Math.PI, 1.571, 0]}>
              <mesh name="Cube018_Material_0" geometry={nodes.Cube018_Material_0.geometry} material={materials.Material} />
            </group>
          </group>
          <group name="Bone004_05" position={[-26.58, 0, 0]} rotation={[-1.566, 0, Math.PI / 2]}>
            <group name="Cylinder005" position={[0, 0.209, 0]} rotation={[Math.PI / 2, -1.571, 0]}>
              <mesh name="Cylinder005_Material_0" geometry={nodes.Cylinder005_Material_0.geometry} material={materials.Material} />
            </group>
          </group>
          <group name="Bone005_06" position={[-13.49, 9.772, -1.339]} rotation={[-0.002, 1.571, 0]}>
            <group name="Cylinder003" position={[-1.339, -9.772, 34.098]} rotation={[0, -Math.PI / 2, 0]}>
              <mesh name="Cylinder003_Material_0" geometry={nodes.Cylinder003_Material_0.geometry} material={materials.Material} />
            </group>
          </group>
          <group name="Bone006_07" position={[-13.49, -9.772, -1.339]} rotation={[3.139, 1.571, 0]}>
            <group name="Cylinder010" position={[1.339, -9.772, 34.098]} rotation={[-Math.PI, 1.571, 0]}>
              <mesh name="Cylinder010_Material_0" geometry={nodes.Cylinder010_Material_0.geometry} material={materials.Material} />
            </group>
          </group>
          <group name="Bone007_08" position={[-9.763, 20.149, -1.887]} rotation={[Math.PI / 2, 1.561, 0]}>
            <group name="Cube023" position={[-20.149, 1.887, 30.371]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]}>
              <mesh name="Cube023_Material_0" geometry={nodes.Cube023_Material_0.geometry} material={materials.Material} />
            </group>
          </group>
          <group name="Bone008_09" position={[-9.763, -20.149, -1.887]} rotation={[1.571, 1.565, 0]}>
            <group name="Cube012" position={[20.149, 1.887, 30.371]} rotation={[-Math.PI / 2, 0, -1.571]}>
              <mesh name="Cube012_Material_0" geometry={nodes.Cube012_Material_0.geometry} material={materials.Material} />
            </group>
          </group>
          <group name="Bone009_010" position={[-10.388, 4.011, -3.594]} rotation={[-Math.PI / 2, 0, -0.432]}>
            <group name="Bone010_011" position={[0, 3.168, 0]} rotation={[0, 0, -1.138]}>
              <group name="Cube003" position={[9.341, 5.077, -4.011]} rotation={[Math.PI / 2, 1.571, 0]}>
                <mesh name="Cube003_Material_0" geometry={nodes.Cube003_Material_0.geometry} material={materials.Material} />
              </group>
            </group>
            <group name="Cylinder001" position={[1.456, -6.437, -4.011]} rotation={[Math.PI / 2, -0.076, 0]}>
              <mesh name="Cylinder001_Material_0" geometry={nodes.Cylinder001_Material_0.geometry} material={materials.Material} />
            </group>
          </group>
          <group name="Bone011_012" position={[9.075, -0.319, -3.025]} rotation={[-Math.PI / 2, 0, -0.432]}>
            <group name="Bone012_013" position={[0, 3.168, 0]} rotation={[0, 0, -1.139]}>
              <group name="Cube027" position={[-0.643, 0.675, 0.319]} rotation={[Math.PI / 2, Math.PI / 2, 0]}>
                <mesh name="Cube027_Material_0" geometry={nodes.Cube027_Material_0.geometry} material={materials.Material} />
              </group>
            </group>
            <group name="Cylinder009" position={[0.571, 3.378, 0.319]} rotation={[Math.PI / 2, -0.076, 0]}>
              <mesh name="Cylinder009_Material_0" geometry={nodes.Cylinder009_Material_0.geometry} material={materials.Material} />
            </group>
          </group>
        </group>
        <mesh name="Cube_Material_0" geometry={nodes.Cube_Material_0.geometry} material={materials.Material} position={[-24.603, 2.866, 0]} rotation={[-Math.PI / 2, 0, 0]} />
      </group>
    </group>
  )
}

useGLTF.preload('/spaceship_cb1-transformed.glb')
